jobs: 18000
cluster: "sbatch -p gen-mk-compute-1,interactive,dgx -t {resources.time_min} --mem={resources.mem_mb} -c {resources.cpus} -o logs_slurm/{rule}_{wildcards} -e logs_slurm/{rule}_{wildcards} --mail-type=FAIL --mail-user=herber4@clemson.edu"
resources: [cpus=856, mem_mb=3662000]
